### ISSUE TITLE
An internal Server Error occurs when installing

### ISSUE THREAD

**Issue by guitarmanvt** [soltra-adapters/adapter-email-extract#4]
Moved from https://github.com/Soltra/repository/issues/870 (see there for complete history)

Steps to reproduce:

Login to Edge 2.9.0_Pre5
Navigate to Admin then Adapter
Install email_extract_adapter.tgz' viaSoltra Downloads`
Click on Select and upload

Actual:Internal Server Error.

**Comment by 3rdpaw** [comment]
Fixed in commit 55e44fe
